---
- name: Creates App directory
  file:
    path: ~/app
    state: directory

- name: Upload dist to app directory
  copy:
    src: files/dist.zip
    dest: "~/app"

- name: Install dependencies
  become: true
  shell: |
    npm i pm2
  ignore_errors: yes
  
- name: Start backend
  become: true
  shell:  pm2 start ~/app/dist/main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    VERSION: 1
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: ~/app/migrations
    TYPEORM_MIGRATIONS: ~/app/migrations/*.ts
    TYPEORM_ENTITIES: ~/app/modules/domain/**/*.entity.js
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"