---
- name: Creates App directory
  file:
    path: ~/app
    state: directory

- name: Upload dist to app directory
  copy:
    src: files/dist.tar
    dest: "~/app"

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/app/
    tar xf /home/ubuntu/app/dist.tar
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm i @nestjs/core
    npm i @nestjs/swagger
    npm install -g pm2
  ignore_errors: yes
  
- name: Start backend
  become: true
  shell:  /usr/bin/pm2 start /home/ubuntu/app/dist/main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    VERSION: 1
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: ~/app/migrations
    TYPEORM_MIGRATIONS: ~/app/migrations/*.ts
    TYPEORM_ENTITIES: ~/app/modules/domain/**/*.entity.js
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"