version: 2.1

jobs:

  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            #Spical handling for AWS Linux
            yum update -y
            yum install -y python3.7
            yum install -y unzip           
            yum install -y tar  
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            .~/.nvm/nvm.sh
            nvm install 4.4.5            



          
  deploy-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fb:37:85:ce:0b:ca:dd:b3:ca:41:c8:71:3e:b6:ed:ca"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install zip unzip python ansible python-pip && pip install awscli





  
workflows:
  default:
    jobs:
      - deploy-frontend
      - deploy-backend
